export * from './ping.controller';
export * from './user.controller';
export * from './cliente.controller';
export * from './departamento.controller';
export * from './dispositivo.controller';
export * from './empleado.controller';
export * from './empleado2.controller';
export * from './orden.controller';
export * from './orden2.controller';
